// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHzVexayS05WrevsKJDDB67PtGcxN83P4',
    appId: '1:505810867245:web:af61cc5c7613b0e68094a4',
    messagingSenderId: '505810867245',
    projectId: 'quizapp-8c34f',
    authDomain: 'quizapp-8c34f.firebaseapp.com',
    storageBucket: 'quizapp-8c34f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzNs04DO_1mbtNAy4KZsxsHVfhXevCFH0',
    appId: '1:505810867245:android:0a143b3bf6c13e8d8094a4',
    messagingSenderId: '505810867245',
    projectId: 'quizapp-8c34f',
    storageBucket: 'quizapp-8c34f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOaAgNQEQnlInnMhRTjSVdmjM2TIOWj6c',
    appId: '1:505810867245:ios:c6ff222e82f7dc428094a4',
    messagingSenderId: '505810867245',
    projectId: 'quizapp-8c34f',
    storageBucket: 'quizapp-8c34f.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOaAgNQEQnlInnMhRTjSVdmjM2TIOWj6c',
    appId: '1:505810867245:ios:c6ff222e82f7dc428094a4',
    messagingSenderId: '505810867245',
    projectId: 'quizapp-8c34f',
    storageBucket: 'quizapp-8c34f.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHzVexayS05WrevsKJDDB67PtGcxN83P4',
    appId: '1:505810867245:web:abd810eaf79d7ed98094a4',
    messagingSenderId: '505810867245',
    projectId: 'quizapp-8c34f',
    authDomain: 'quizapp-8c34f.firebaseapp.com',
    storageBucket: 'quizapp-8c34f.firebasestorage.app',
  );
}
